#!/bin/bash

echo "-------------------------------------------------------"
echo "=> Running build hook"
echo "-------------------------------------------------------"

set -exuo pipefail

repo=master

[ "$DOCKER_TAG" != "latest" ] && repo=$DOCKER_TAG

docker build \
	--build-arg REPO=$repo \
	--tag $IMAGE_NAME \
	-f $DOCKERFILE_PATH .

echo "-------------------------------------------------------"
