#!/bin/bash

echo "-------------------------------------------------------"
echo "=> Running post_checkout hook"
echo "-------------------------------------------------------"

echo "ARGS: $*"

env | sort

exit 2
